const BIO_DATA = {
    "Adela_Irusta": "Adela Irusta",
    "Agustina_Montano": "Agustina Montano",
    "Antonio_Teixeira": "Antonio Teixeira",
    "Ayelen_Savid_Teixeira": "La Aye",
    "Carmen_Beatriz_Teixeira": "Carmencita",
    "Carmen_Garcia_Zavalla": "Carmen Garcia Zavalla",
    "Cristobal_Garcia": "Cristobal Garcia",
    "Dolores_Gudino": "Dolores Gudino",
    "Domingo_del_Rosario_Savid_Mansilla": "Domingo del Rosario Savid Mansilla",
    "Domingo_Garcia_de_Rosas": "Domingo Garcia de Rosas",
    "Fenelon_Savid": "Fene",
    "Fenelon_Victoriano_Torres_Martinez": "Fenelón Victoriano Torres Martínez",
    "Fernando_Garcia": "Fernando Garcia",
    "Gregorio_Savid_Luque": "Gregorio Savid Luque",
    "Isabel_Estaurofila_Gudino": "Isabel Estaurofila Gudino",
    "Isabel_Mansilla": "Isabel Mansilla",
    "Javier_Carballo": "Javier Carballo",
    "Javier_Francisco_Savid_Teixeira": "El Javi",
    "Joao_Teixeira": "Joao Teixeira",
    "Jose_Gregorio_Savid_Carballo": "Jose Gregorio Savid Carballo",
    "Jose_Tomas_Savid_Garcia": "Jose Tomas Savid Garcia",
    "Juana_de_Zavalia_y_Garcia": "Juana de Zavalia y Garcia",
    "Juana_Josefa_Zavalia": "Juana Josefa Zavalia",
    "Juan_Cristobal_Teixeira": "El titi",
    "Juan_Irusta": "Juan Irusta",
    "Juan_Jesus_Teixeira": "El Tatá\nEl Caco",
    "Luis_Eduardo_Savid": "El Lichi",
    "Maria_Angela_Torres": "Alita",
    "Maria_Angeles_Omil": "La Yaya",
    "Maria_Fredebinda_Irusta": "La abuela pollito",
    "Maria_Isabel_Teixeira": "Marita",
    "Maria_Luisa_Garcia": "La Tatá",
    "Maria_Pucheta": "Maria Pucheta",
    "Patricia_OConnor": "Patricia O'Connor",
    "Rafael_Garcia": "Rafael Garcia",
    "Rayen_Savid_Teixeira": "Ra",
    "Rosario_Carballo_y_Carrillo": "Rosario Carballo y Carrillo",
    "Rosario_Carrilo_Albornoz": "Rosario Carrilo Albornoz",
    "Tomas_Garcia_Montano": "Tomas Garcia Montano",
    "Mercedes_Endrek": "Mercedes Endrek",
    "Moises_Omil": "Moisés Omil",
    "Angela_Paez": "Ángela Páez",
    "Antonio_Omil": "Antonio Omil",
    "Fenelon_Torres_Recabarren": "Fenelón Torres Recabarren",
    "Rita_Martinez": "Rita Martínez",
    "Emiliano_Enderek": "Emiliano Enderek",
    "Eloisa_Diaz": "Eloísa Díaz",
    "Hugo_Gines_de_Paco": "Hugo Ginés de Paco",
    "Mayra_de_Paco": "Mayra de Paco",
    "Zeferina_Freitas": "Zeferina Freitas"
};